name: quiz
description: Quiz.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2

  # State management and DI
  flutter_bloc: ^8.1.1

  # Network
  http: ^0.13.5

  # Objects
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^1.23.0
  cloud_firestore: ^3.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  